root: true
env:
  browser: true
  es2021: true
  amd: true
  webextensions: true
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:vue/essential"
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  "@typescript-eslint/no-var-requires": 0
