/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as InfoGroup from "./InfoGroup";
export interface IPayloadGroupArgs {
    base?: InfoGroup.InfoGroup;
    props?: Buffer;
}
export class PayloadGroup {
    public base?: InfoGroup.InfoGroup;
    public props?: Buffer;
    constructor(args?: IPayloadGroupArgs) {
        if (args != null && args.base != null) {
            this.base = args.base;
        }
        if (args != null && args.props != null) {
            this.props = args.props;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("PayloadGroup");
        if (this.base != null) {
            output.writeFieldBegin("base", thrift.Thrift.Type.STRUCT, 1);
            this.base.write(output);
            output.writeFieldEnd();
        }
        if (this.props != null) {
            output.writeFieldBegin("props", thrift.Thrift.Type.STRING, 2);
            output.writeBinary(this.props);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): PayloadGroup {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: InfoGroup.InfoGroup = InfoGroup.InfoGroup.read(input);
                        _args.base = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: Buffer = input.readBinary();
                        _args.props = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new PayloadGroup(_args);
    }
}
