/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as Error from "./Error";
export interface IRspPlayerRequestArgs {
    result?: Error.Error;
    type?: string;
    data?: Buffer;
}
export class RspPlayerRequest {
    public result?: Error.Error;
    public type?: string;
    public data?: Buffer;
    constructor(args?: IRspPlayerRequestArgs) {
        if (args != null && args.result != null) {
            this.result = args.result;
        }
        if (args != null && args.type != null) {
            this.type = args.type;
        }
        if (args != null && args.data != null) {
            this.data = args.data;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("RspPlayerRequest");
        if (this.result != null) {
            output.writeFieldBegin("result", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.result);
            output.writeFieldEnd();
        }
        if (this.type != null) {
            output.writeFieldBegin("type", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.type);
            output.writeFieldEnd();
        }
        if (this.data != null) {
            output.writeFieldBegin("data", thrift.Thrift.Type.STRING, 3);
            output.writeBinary(this.data);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): RspPlayerRequest {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: Error.Error = input.readI32();
                        _args.result = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.type = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: Buffer = input.readBinary();
                        _args.data = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new RspPlayerRequest(_args);
    }
}
