name: CU Helper Pack Extension CI
on:
  push:
    tags:
      - 'v*'
jobs:
  build-chrome-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependency
        run: yarn install --immutable
      - name: Build and pack
        run: ./node_modules/.bin/webpack --config webpack.js
      - name: Pack to zip file
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: dist
          zipFilePath: build/extension.zip
      - name: Pack to crx file
        uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.1
        with:
          zipFilePath: build/extension.zip
          crxFilePath: build/extension.crx
          privateKey: ${{ secrets.EXTENSION_PK }}
      - name: Upload extension
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: |
            build/extension.crx
            build/extension.zip
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: build/*
          tag: ${{ github.ref_name }}
          overwrite: true
      - name: Update to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'upload'
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: eaibhjlbakfdbmalpoefnpoaccijhgbh
          zip_file: build/extension.zip
